redpitaya:
  host: rp-f06549.local
  scpi_port: 5000
  user: root
  remote_runs_dir: /root/piezo_runs   # where temporary runs will be stored on RP

run:
  sample_name: PVDF_sample_A
  periods: 10
  repetitions: 3

sweep:
  resistances_ohm: [1000, 10000, 100000]     # manual decade box values you will dial
  frequencies_hz: [5, 10, 20, 40]

output:
  local_runs_dir: runs
